server:
  port: 8081

spring:
  application:
    name: quantcrux-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/quantcrux
    username: quant_user
    password: quant_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  
  security:
    user:
      name: admin
      password: admin

# JWT Configuration
jwt:
  secret: quantcrux-jwt-secret-key-for-token-generation-and-validation-2024-very-long-secure-key
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000,http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Session Configuration
session:
  cleanup-interval: 3600000 # 1 hour in milliseconds
  max-sessions-per-user: 5

# Security Configuration
security:
  max-login-attempts: 5
  account-lockout-duration: 1800000 # 30 minutes in milliseconds
  password-expiry-days: 90

# Logging
logging:
  level:
    com.quantcrux: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,sessions
  endpoint:
    health:
      show-details: always
    sessions:
      enabled: true

# Application specific configuration
app:
  name: QuantCrux
  version: 1.0.0
  description: Quantitative Finance Platform
  contact:
    email: support@quantcrux.com
    name: QuantCrux Support Team